language: java
jdk:
  - oraclejdk8
os : osx
before_install:
  - brew update
  - brew install thrift
  - brew install gradle
  - "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-macosx-x64.dmg"
  - hdiutil mount jdk-8u66-macosx-x64.dmg
  - sudo installer -pkg /Volumes/JDK\ 8\ Update\ 66/JDK\ 8\ Update\ 66.pkg -target LocalSystem